name: Continuous Deployment Practice

on: [push]

jobs:
        deploy:
                name: Deployment
                runs-on: ubuntu-18.04
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: Run
                          env:
                                  IP: 13.209.14.51
                          run: |
                                  export AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }}
                                  export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
                                  aws s3 cp index.html s3://workshop-practices/13.209.14.51 --acl public-read

